#!/usr/bin/env bash
set -euo pipefail

# Build the released sample-level sequencing / assembly summary and
# MAG-associated coverage QC tables for the Scientific Data Data Descriptor.
#
# ---------------------------------------------------------------------------
# Study input preparation
# ---------------------------------------------------------------------------
# Each composite rhizosphere sample was sequenced on two PacBio Revio
# SMRT Cells. In the public SRA deposit, the two sequencing runs for a sample
# are represented by two SRR accessions.
#
# If starting from SRA FASTQ files, prepare SAMPLE.fasta by:
#
#   1. downloading the two run-level FASTQ files for that sample;
#   2. converting each FASTQ file to FASTA with seqtk v1.3-r106; and
#   3. concatenating the two run-level FASTA files into one SAMPLE.fasta.
#
# Example:
#
#   fasterq-dump SRR_RUN1
#   fasterq-dump SRR_RUN2
#
#   seqtk seq -A SRR_RUN1.fastq > SRR_RUN1.fasta
#   seqtk seq -A SRR_RUN2.fastq > SRR_RUN2.fasta
#
#   cat SRR_RUN1.fasta SRR_RUN2.fasta > Con.fasta
#
# Replace Con with the corresponding sample ID and use the two SRR accessions
# assigned to that sample.
#
# This is simple concatenation of the two PacBio HiFi read sets, not
# paired-end read merging. The combined SAMPLE.fasta represents the same
# two-run read set that was used before sample-wise metaMDBG assembly.
#
# SRA Toolkit is needed only when starting from SRR accessions. If the two
# run-level FASTQ files have already been downloaded, only seqtk is required
# for the FASTQ-to-FASTA conversion.
#
# ---------------------------------------------------------------------------
# Upstream analysis provenance
# ---------------------------------------------------------------------------
# The MAG recovery workflow was run with
# pb-metagenomics-tools/HiFi-MAG-Pipeline v3.3.2.
#
# Relevant completed pipeline outputs used here are:
#
#   path/to/HiFi-MAG-Pipeline/
#   ├── 2-bam/
#   │   ├── Con.JGI.depth.txt
#   │   ├── CW1.JGI.depth.txt
#   │   └── ...
#   └── 8-summary/
#       ├── Con/
#       │   └── Con.HiFi_MAG.summary.txt
#       ├── CW1/
#       │   └── CW1.HiFi_MAG.summary.txt
#       └── ...
#
# The *.JGI.depth.txt files are generated upstream by
# jgi_summarize_bam_contig_depths from MetaBAT2 v2.15.
#
# The sample-level HiFi_MAG.summary.txt files provide MAG membership,
# including the MAG Name and Contig_Names fields. This public script therefore
# does not depend on a private intermediate metadata table.
#
# ---------------------------------------------------------------------------
# Files supplied to this script
# ---------------------------------------------------------------------------
# INPUT_DIR must contain:
#
#   ./inputs/
#       Con.fasta
#       Con.contigs.fasta
#       CW1.fasta
#       CW1.contigs.fasta
#       ...
#
# IMPORTANT:
#   SAMPLE.fasta          = the two run-level PacBio HiFi read FASTAs
#                           concatenated for that sample
#   SAMPLE.contigs.fasta  = the corresponding metaMDBG assembly
#
# *_half / *_quarter / *_one_eighth files are not used.
#
# ---------------------------------------------------------------------------
# Software required to execute this script
# ---------------------------------------------------------------------------
# - Bash
# - SeqKit v2.12.0
# - Python 3 (standard library only)
#
# Optional preparation software when starting from SRA:
# - SRA Toolkit (for fasterq-dump)
# - seqtk v1.3-r106 (for FASTQ -> FASTA conversion)
#
# The upstream JGI depth tables and MAG summary files must already have been
# generated by HiFi-MAG-Pipeline; this script does not rerun read mapping,
# MetaBAT2, CheckM2, GTDB-Tk, or MAG recovery.
#
# ---------------------------------------------------------------------------
# MAG-associated HiFi signal
# ---------------------------------------------------------------------------
# For all contigs assigned to primary MAGs in a sample, the script calculates:
#
#   MAG depth-weighted bases =
#       sum(contigLen * totalAvgDepth)
#
# and:
#
#   MAG-associated HiFi bases (%) =
#       100 * MAG depth-weighted bases / raw HiFi total bases
#
# This is a depth-weighted sequencing signal associated with MAG contigs.
# It should not be interpreted as a direct read-recruitment fraction.
#
# ---------------------------------------------------------------------------
# Example
# ---------------------------------------------------------------------------
#   INPUT_DIR=./inputs \
#   PIPELINE_ROOT=path/to/HiFi-MAG-Pipeline \
#   bash data_processing/build_sequencing_assembly_mag_coverage_tables.sh
#
# CPU use:
#   SeqKit is forced to one thread and samples are processed sequentially.

INPUT_DIR="${INPUT_DIR:-./inputs}"
PIPELINE_ROOT="${PIPELINE_ROOT:-path/to/HiFi-MAG-Pipeline}"
JGI_DIR="${JGI_DIR:-${PIPELINE_ROOT}/2-bam}"
SUMMARY_DIR="${SUMMARY_DIR:-${PIPELINE_ROOT}/8-summary}"

OUT="${OUT:-1-01_sequencing_assembly_summary.tsv}"
QC_OUT="${QC_OUT:-1-02_mag_associated_coverage_qc.tsv}"
RAW_OUT="${RAW_OUT:-sequencing_assembly_seqkit_stats.tsv}"

SAMPLES=(Con CW1 CW2 GY1 MP1 MP2 NH2 NH3 PH1 PH2 US1)

command -v seqkit >/dev/null 2>&1 || {
    echo "ERROR: seqkit not found in PATH" >&2
    exit 1
}

command -v python3 >/dev/null 2>&1 || {
    echo "ERROR: python3 not found in PATH" >&2
    exit 1
}

# ---------- Validate exact input and pipeline files ----------
for s in "${SAMPLES[@]}"; do
    reads="${INPUT_DIR}/${s}.fasta"
    assembly="${INPUT_DIR}/${s}.contigs.fasta"
    jgi="${JGI_DIR}/${s}.JGI.depth.txt"
    summary="${SUMMARY_DIR}/${s}/${s}.HiFi_MAG.summary.txt"

    [[ -f "$reads" ]] || {
        echo "ERROR: missing combined raw HiFi reads: $reads" >&2
        exit 1
    }

    [[ -f "$assembly" ]] || {
        echo "ERROR: missing assembly: $assembly" >&2
        exit 1
    }

    [[ -f "$jgi" ]] || {
        echo "ERROR: missing JGI depth file: $jgi" >&2
        exit 1
    }

    [[ -f "$summary" ]] || {
        echo "ERROR: missing HiFi-MAG summary: $summary" >&2
        exit 1
    }
done

echo "[INFO] All 11 read, assembly, JGI-depth, and MAG-summary inputs found."
echo "[INFO] SeqKit threads = 1"

# ---------- Collect SeqKit statistics sequentially ----------
: > "$RAW_OUT"

for s in "${SAMPLES[@]}"; do
    for dtype in reads assembly; do
        if [[ "$dtype" == "reads" ]]; then
            f="${INPUT_DIR}/${s}.fasta"
        else
            f="${INPUT_DIR}/${s}.contigs.fasta"
        fi

        echo "[INFO] ${s}: ${dtype} -> ${f}" >&2

        tmp="$(mktemp)"
        seqkit stats -j 1 -a -T "$f" > "$tmp"

        if [[ ! -s "$RAW_OUT" ]]; then
            awk 'NR==1 {print "sample_id\tdata_type\t" $0}' "$tmp" >> "$RAW_OUT"
        fi

        awk -v s="$s" -v d="$dtype" 'NR==2 {print s "\t" d "\t" $0}' "$tmp" >> "$RAW_OUT"
        rm -f "$tmp"
    done
done

# ---------- Parse MAG membership + JGI depth and build final tables ----------
python3 - "$RAW_OUT" "$SUMMARY_DIR" "$JGI_DIR" "$OUT" "$QC_OUT" <<'PY'
import csv
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

raw_path = Path(sys.argv[1])
summary_dir = Path(sys.argv[2])
jgi_dir = Path(sys.argv[3])
out_path = Path(sys.argv[4])
qc_path = Path(sys.argv[5])

samples = [
    "Con", "CW1", "CW2", "GY1", "MP1", "MP2",
    "NH2", "NH3", "PH1", "PH2", "US1"
]


def clean_int(value):
    return int(float(str(value).strip().replace(",", "")))


def split_contigs(value):
    """Split Contig_Names robustly across common delimiters."""
    value = (value or "").strip()
    if not value:
        return []
    return [x for x in re.split(r"[,;|\s]+", value) if x]


seq_stats = {}
with raw_path.open(newline="", encoding="utf-8") as fh:
    reader = csv.DictReader(fh, delimiter="\t")
    fields = set(reader.fieldnames or [])
    required = {"sample_id", "data_type", "num_seqs", "sum_len", "N50"}
    missing = required - fields
    if missing:
        raise SystemExit(
            f"ERROR: SeqKit output missing columns {sorted(missing)}; "
            f"available={reader.fieldnames}"
        )
    for row in reader:
        seq_stats[(row["sample_id"], row["data_type"])] = row

sample_contig_assignments = defaultdict(list)
sample_mag_counts = Counter()
seen_mag_ids = set()

for sample in samples:
    summary_path = summary_dir / sample / f"{sample}.HiFi_MAG.summary.txt"
    with summary_path.open(
        newline="",
        encoding="utf-8-sig",
        errors="replace",
    ) as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        fields = set(reader.fieldnames or [])
        required = {"Name", "Contig_Names", "Contig_Number"}
        missing = required - fields
        if missing:
            raise SystemExit(
                f"ERROR: {summary_path} missing columns {sorted(missing)}; "
                f"available={reader.fieldnames}"
            )

        for row in reader:
            bin_name = (row.get("Name") or "").strip()
            if not bin_name:
                continue

            mag_id = f"{sample}_{bin_name}"
            if mag_id in seen_mag_ids:
                raise SystemExit(f"ERROR: duplicate MAG ID: {mag_id}")
            seen_mag_ids.add(mag_id)

            contigs = split_contigs(row.get("Contig_Names"))
            expected_n = clean_int(row["Contig_Number"])

            if len(contigs) != expected_n:
                raise SystemExit(
                    f"ERROR: {mag_id}: Contig_Number={expected_n} but "
                    f"{len(contigs)} contigs were parsed from Contig_Names"
                )

            if not contigs:
                raise SystemExit(f"ERROR: no Contig_Names for MAG {mag_id}")

            sample_mag_counts[sample] += 1
            for contig in contigs:
                sample_contig_assignments[sample].append((mag_id, contig))

total_mags = sum(sample_mag_counts.values())
if total_mags != 6505:
    raise SystemExit(
        f"ERROR: expected 6505 primary MAGs but found {total_mags}. "
        "Check that the correct HiFi-MAG-Pipeline summaries were supplied."
    )

results = {}
qc_rows = []

for sample in samples:
    jgi_path = jgi_dir / f"{sample}.JGI.depth.txt"
    jgi = {}

    with jgi_path.open(
        newline="",
        encoding="utf-8",
        errors="replace",
    ) as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        fields = set(reader.fieldnames or [])
        required = {"contigName", "contigLen", "totalAvgDepth"}
        missing = required - fields
        if missing:
            raise SystemExit(
                f"ERROR: {jgi_path} missing columns {sorted(missing)}; "
                f"available={reader.fieldnames}"
            )

        for row in reader:
            contig = row["contigName"].strip()
            if contig in jgi:
                raise SystemExit(
                    f"ERROR: duplicate contig in JGI file {jgi_path}: {contig}"
                )
            try:
                length = int(float(row["contigLen"]))
                depth = float(row["totalAvgDepth"])
            except ValueError as exc:
                raise SystemExit(
                    f"ERROR parsing {jgi_path}: {exc}"
                ) from exc

            if length <= 0:
                raise SystemExit(
                    f"ERROR: {sample}: non-positive contig length for {contig}"
                )
            if depth < 0:
                raise SystemExit(
                    f"ERROR: {sample}: negative totalAvgDepth for {contig}"
                )

            jgi[contig] = (length, depth)

    assignments = sample_contig_assignments[sample]
    assignment_counts = Counter(contig for _, contig in assignments)
    unique_mag_contigs = set(assignment_counts)

    duplicate_contigs = sorted(
        contig for contig, count in assignment_counts.items() if count > 1
    )
    missing_in_jgi = sorted(
        contig for contig in unique_mag_contigs if contig not in jgi
    )

    if duplicate_contigs:
        preview = ", ".join(duplicate_contigs[:10])
        raise SystemExit(
            f"ERROR: {sample}: {len(duplicate_contigs)} contigs are assigned "
            f"to more than one MAG (examples: {preview})."
        )

    if missing_in_jgi:
        preview = ", ".join(missing_in_jgi[:10])
        raise SystemExit(
            f"ERROR: {sample}: {len(missing_in_jgi)} MAG contigs were not "
            f"found in the JGI depth table (examples: {preview})."
        )

    mag_bp = sum(jgi[c][0] for c in unique_mag_contigs)

    mag_depth_weighted_bases = sum(
        jgi[c][0] * jgi[c][1]
        for c in unique_mag_contigs
    )

    all_assembly_depth_weighted_bases = sum(
        length * depth for length, depth in jgi.values()
    )

    rr = seq_stats[(sample, "reads")]
    aa = seq_stats[(sample, "assembly")]

    raw_read_count = clean_int(rr["num_seqs"])
    raw_bp = clean_int(rr["sum_len"])
    read_n50 = clean_int(rr["N50"])

    assembly_contigs = clean_int(aa["num_seqs"])
    assembly_bp = clean_int(aa["sum_len"])
    assembly_n50 = clean_int(aa["N50"])

    if raw_bp <= 0:
        raise SystemExit(f"ERROR: {sample}: raw HiFi total bases <= 0")

    mag_raw_pct = 100.0 * mag_depth_weighted_bases / raw_bp

    if all_assembly_depth_weighted_bases > 0:
        mag_of_assembly_mapped_pct = (
            100.0
            * mag_depth_weighted_bases
            / all_assembly_depth_weighted_bases
        )
    else:
        mag_of_assembly_mapped_pct = math.nan

    results[sample] = {
        "sample_id": sample,
        "hifi_read_count": raw_read_count,
        "hifi_yield_bp": raw_bp,
        "hifi_yield_Gb": raw_bp / 1e9,
        "read_N50_bp": read_n50,
        "assembly_contig_count": assembly_contigs,
        "assembly_size_bp": assembly_bp,
        "assembly_size_Gb": assembly_bp / 1e9,
        "assembly_contig_N50_bp": assembly_n50,
        "primary_MAG_count": sample_mag_counts[sample],
        "MAG_contig_count": len(unique_mag_contigs),
        "MAG_total_contig_bp": mag_bp,
        "MAG_associated_depth_weighted_bases": mag_depth_weighted_bases,
        "MAG_associated_HiFi_bases_percent": mag_raw_pct,
        "MAG_fraction_of_assembly_mapped_bases_percent": (
            mag_of_assembly_mapped_pct
        ),
    }

    qc_rows.append({
        "sample_id": sample,
        "primary_MAG_count": sample_mag_counts[sample],
        "MAG_contig_assignments": len(assignments),
        "unique_MAG_contigs": len(unique_mag_contigs),
        "duplicate_MAG_contigs": len(duplicate_contigs),
        "MAG_contigs_missing_in_JGI": len(missing_in_jgi),
        "JGI_contig_count": len(jgi),
        "raw_HiFi_bases": raw_bp,
        "all_assembly_depth_weighted_bases": (
            all_assembly_depth_weighted_bases
        ),
        "MAG_depth_weighted_bases": mag_depth_weighted_bases,
    })

main_fields = [
    "sample_id",
    "hifi_read_count",
    "hifi_yield_bp",
    "hifi_yield_Gb",
    "read_N50_bp",
    "assembly_contig_count",
    "assembly_size_bp",
    "assembly_size_Gb",
    "assembly_contig_N50_bp",
    "primary_MAG_count",
    "MAG_contig_count",
    "MAG_total_contig_bp",
    "MAG_associated_depth_weighted_bases",
    "MAG_associated_HiFi_bases_percent",
    "MAG_fraction_of_assembly_mapped_bases_percent",
]

with out_path.open("w", newline="", encoding="utf-8") as fh:
    writer = csv.DictWriter(
        fh,
        fieldnames=main_fields,
        delimiter="\t",
        lineterminator="\n",
    )
    writer.writeheader()

    for sample in samples:
        row = results[sample].copy()
        row["hifi_yield_Gb"] = f'{row["hifi_yield_Gb"]:.3f}'
        row["assembly_size_Gb"] = f'{row["assembly_size_Gb"]:.3f}'
        row["MAG_associated_depth_weighted_bases"] = (
            f'{row["MAG_associated_depth_weighted_bases"]:.3f}'
        )
        row["MAG_associated_HiFi_bases_percent"] = (
            f'{row["MAG_associated_HiFi_bases_percent"]:.3f}'
        )
        row["MAG_fraction_of_assembly_mapped_bases_percent"] = (
            f'{row["MAG_fraction_of_assembly_mapped_bases_percent"]:.3f}'
        )
        writer.writerow(row)

qc_fields = list(qc_rows[0].keys())

with qc_path.open("w", newline="", encoding="utf-8") as fh:
    writer = csv.DictWriter(
        fh,
        fieldnames=qc_fields,
        delimiter="\t",
        lineterminator="\n",
    )
    writer.writeheader()

    for row in qc_rows:
        output_row = row.copy()
        output_row["all_assembly_depth_weighted_bases"] = (
            f'{output_row["all_assembly_depth_weighted_bases"]:.3f}'
        )
        output_row["MAG_depth_weighted_bases"] = (
            f'{output_row["MAG_depth_weighted_bases"]:.3f}'
        )
        writer.writerow(output_row)

print(f"[INFO] Primary MAGs parsed: {total_mags}")
print(f"[DONE] wrote {out_path}")
print(f"[DONE] wrote {qc_path}")
PY

echo
echo "[RESULT: main summary]"
column -t -s $'\t' "$OUT" 2>/dev/null || cat "$OUT"

echo
echo "[QC]"
column -t -s $'\t' "$QC_OUT" 2>/dev/null || cat "$QC_OUT"
