#!/usr/bin/env python3
"""
Build the released 2-02_mag_metadata.tsv table with contig-length-weighted
MAG depth from pb-metagenomics-tools/HiFi-MAG-Pipeline outputs.

Upstream data generation
------------------------
This script is intended to be run after processing the study FASTA/FASTQ
sequence inputs with pb-metagenomics-tools/HiFi-MAG-Pipeline. It reconstructs
the released primary-MAG metadata table, 2-02_mag_metadata.tsv.

Relevant upstream outputs are expected in:

    path/to/HiFi-MAG-Pipeline/
    ├── 2-bam/
    │   ├── <sample>.JGI.depth.txt
    │   └── ...
    └── 8-summary/
        ├── <sample>/
        │   └── <sample>.HiFi_MAG.summary.txt
        └── ...

For example, if pb-metagenomics-tools is installed under:

    $HOME/projects/pb-metagenomics-tools

the pipeline root would typically be:

    $HOME/projects/pb-metagenomics-tools/HiFi-MAG-Pipeline

The *.JGI.depth.txt files are upstream outputs from
jgi_summarize_bam_contig_depths (MetaBAT2). The HiFi_MAG.summary.txt files
contain the MAG-level quality and taxonomy fields generated by the pipeline.
This script reuses those outputs; it does not rerun read mapping, CheckM2,
GTDB-Tk, or depth estimation.

Requirements
------------
- Python 3 (standard library only)
- Completed pb-metagenomics-tools/HiFi-MAG-Pipeline outputs
- For the upstream pipeline, the corresponding software dependencies
  (including MetaBAT2/jgi_summarize_bam_contig_depths, CheckM2, and GTDB-Tk)
  must already have been run by HiFi-MAG-Pipeline.

MAG average depth
-----------------
For each MAG, average depth is calculated from the JGI depth table as:

    sum(contigLen * totalAvgDepth) / sum(contigLen)

where the sum is taken over all contigs assigned to that MAG.

Released output
---------------
The resulting table corresponds to the released:

    2-02_mag_metadata.tsv

and contains:
    mag_id
    sample_id
    completeness
    contamination
    contig_count
    average_depth
    genome_size_bp
    gc_content
    gtdb_taxonomy

Example
-------
    python3 build_mag_metadata_with_jgi_depth.py \
        --pipeline-root path/to/HiFi-MAG-Pipeline \
        --out 2-02_mag_metadata.tsv
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path


STUDY_SAMPLES = [
    "CW1",
    "CW2",
    "Con",
    "GY1",
    "MP1",
    "MP2",
    "NH2",
    "NH3",
    "PH1",
    "PH2",
    "US1",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build the released 2-02_mag_metadata.tsv table using "
            "HiFi-MAG-Pipeline summary tables and contig-length-weighted "
            "JGI totalAvgDepth values."
        )
    )
    parser.add_argument(
        "--pipeline-root",
        type=Path,
        required=True,
        help=(
            "Path to the HiFi-MAG-Pipeline directory containing "
            "2-bam/ and 8-summary/."
        ),
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("2-02_mag_metadata.tsv"),
        help="Output TSV path. Default: 2-02_mag_metadata.tsv",
    )
    parser.add_argument(
        "--expected-mags",
        type=int,
        default=6505,
        help="Expected total number of MAGs. Default: 6505",
    )
    return parser.parse_args()


def split_contigs(value: str) -> list[str]:
    """Split Contig_Names robustly across common delimiters."""
    value = value.strip()
    if not value:
        return []

    return [x for x in re.split(r"[,;|\s]+", value) if x]


def load_jgi_depth(path: Path) -> dict[str, tuple[float, float]]:
    """Load contig length and totalAvgDepth from a JGI depth table."""
    if not path.is_file():
        raise FileNotFoundError(path)

    depth_by_contig: dict[str, tuple[float, float]] = {}

    with path.open(newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh, delimiter="\t")

        required = {
            "contigName",
            "contigLen",
            "totalAvgDepth",
        }

        missing = required - set(reader.fieldnames or [])
        if missing:
            raise RuntimeError(
                f"{path}: required columns missing: {sorted(missing)}; "
                f"found={reader.fieldnames}"
            )

        for row in reader:
            name = row["contigName"].strip()

            if not name:
                raise RuntimeError(f"{path}: empty contigName")

            if name in depth_by_contig:
                raise RuntimeError(
                    f"{path}: duplicate contigName: {name}"
                )

            try:
                contig_len = float(row["contigLen"])
                total_avg_depth = float(row["totalAvgDepth"])
            except ValueError as exc:
                raise RuntimeError(
                    f"{path}: invalid contigLen/totalAvgDepth for {name}"
                ) from exc

            if contig_len <= 0:
                raise RuntimeError(
                    f"{path}: non-positive contigLen for {name}: {contig_len}"
                )

            if total_avg_depth < 0:
                raise RuntimeError(
                    f"{path}: negative totalAvgDepth for {name}: "
                    f"{total_avg_depth}"
                )

            depth_by_contig[name] = (
                contig_len,
                total_avg_depth,
            )

    return depth_by_contig


def main() -> None:
    args = parse_args()

    pipeline_root = args.pipeline_root.expanduser().resolve()
    analysis_dir = pipeline_root / "8-summary"
    jgi_dir = pipeline_root / "2-bam"
    out = args.out.expanduser()

    if not pipeline_root.is_dir():
        raise SystemExit(
            f"ERROR: pipeline root not found: {pipeline_root}"
        )

    if not analysis_dir.is_dir():
        raise SystemExit(
            f"ERROR: 8-summary directory not found: {analysis_dir}"
        )

    if not jgi_dir.is_dir():
        raise SystemExit(
            f"ERROR: 2-bam directory not found: {jgi_dir}"
        )

    rows_out: list[dict[str, str]] = []
    missing_contigs: list[tuple[str, list[str]]] = []
    count_mismatch: list[tuple[str, int, int, str]] = []

    duplicate_mag_ids: set[str] = set()
    seen_mag_ids: set[str] = set()

    for sample in STUDY_SAMPLES:
        summary = (
            analysis_dir
            / sample
            / f"{sample}.HiFi_MAG.summary.txt"
        )
        jgi_path = jgi_dir / f"{sample}.JGI.depth.txt"

        if not summary.is_file():
            raise FileNotFoundError(summary)

        if not jgi_path.is_file():
            raise FileNotFoundError(jgi_path)

        print(
            f"[INFO] sample={sample} "
            f"summary={summary} "
            f"jgi_depth={jgi_path}"
        )

        jgi = load_jgi_depth(jgi_path)

        with summary.open(
            newline="",
            encoding="utf-8-sig",
        ) as fh:
            reader = csv.DictReader(fh, delimiter="\t")

            required = {
                "Name",
                "Completeness",
                "Contamination",
                "Contig_Number",
                "Contig_Names",
                "Genome_Size",
                "GC_Content",
                "classification",
            }

            missing_columns = required - set(reader.fieldnames or [])
            if missing_columns:
                raise RuntimeError(
                    f"{summary}: required columns missing: "
                    f"{sorted(missing_columns)}; "
                    f"found={reader.fieldnames}"
                )

            for row in reader:
                bin_name = row["Name"].strip()
                mag_id = f"{sample}_{bin_name}"

                if mag_id in seen_mag_ids:
                    duplicate_mag_ids.add(mag_id)
                seen_mag_ids.add(mag_id)

                contigs = split_contigs(row["Contig_Names"])

                try:
                    expected_n = int(float(row["Contig_Number"]))
                except ValueError as exc:
                    raise RuntimeError(
                        f"{mag_id}: invalid Contig_Number: "
                        f"{row['Contig_Number']!r}"
                    ) from exc

                if len(contigs) != expected_n:
                    count_mismatch.append(
                        (
                            mag_id,
                            expected_n,
                            len(contigs),
                            row["Contig_Names"],
                        )
                    )
                    continue

                weighted_sum = 0.0
                total_len = 0.0
                missing_here: list[str] = []

                for contig in contigs:
                    if contig not in jgi:
                        missing_here.append(contig)
                        continue

                    length, depth = jgi[contig]
                    weighted_sum += length * depth
                    total_len += length

                if missing_here:
                    missing_contigs.append(
                        (mag_id, missing_here)
                    )
                    continue

                if total_len <= 0:
                    raise RuntimeError(
                        f"{mag_id}: total MAG contig length <= 0"
                    )

                average_depth = weighted_sum / total_len

                rows_out.append({
                    "mag_id": mag_id,
                    "sample_id": sample,
                    "completeness": row["Completeness"],
                    "contamination": row["Contamination"],
                    "contig_count": row["Contig_Number"],
                    "average_depth": f"{average_depth:.6f}",
                    "genome_size_bp": row["Genome_Size"],
                    "gc_content": row["GC_Content"],
                    "gtdb_taxonomy": row["classification"],
                })

    if duplicate_mag_ids:
        raise RuntimeError(
            "Duplicate MAG IDs found: "
            f"{sorted(duplicate_mag_ids)[:10]}"
        )

    if count_mismatch:
        print(
            "ERROR: Contig_Number does not match parsed Contig_Names.",
            file=sys.stderr,
        )

        for item in count_mismatch[:10]:
            print(item, file=sys.stderr)

        raise SystemExit(1)

    if missing_contigs:
        print(
            "ERROR: Some MAG contigs were not found in JGI depth tables.",
            file=sys.stderr,
        )

        for mag_id, contigs in missing_contigs[:10]:
            print(
                mag_id,
                contigs[:10],
                file=sys.stderr,
            )

        raise SystemExit(1)

    if len(rows_out) != args.expected_mags:
        raise RuntimeError(
            f"Expected {args.expected_mags} MAGs, "
            f"recovered {len(rows_out)}"
        )

    fieldnames = [
        "mag_id",
        "sample_id",
        "completeness",
        "contamination",
        "contig_count",
        "average_depth",
        "genome_size_bp",
        "gc_content",
        "gtdb_taxonomy",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)

    with out.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=fieldnames,
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(rows_out)

    print(f"[DONE] Wrote: {out}")
    print(f"[INFO] MAGs: {len(rows_out)}")
    print("[INFO] Depth source: JGI totalAvgDepth")
    print(
        "[INFO] MAG average depth: "
        "sum(contigLen * totalAvgDepth) / sum(contigLen)"
    )
    print("[INFO] average_depth precision: 6 decimal places")


if __name__ == "__main__":
    main()

